Toolbar-headline
ElShaer398/Portfolio-setup-and-mobile-first pull request #1
Opened 2022-11-03 19:20 UTC by ElShaer398

Created toolbar and headline sections in 'Portfolio: setup and mobile first' project.

2022-11-03 19:51 UTC, Lizdev-05 requested changes
Hi @ElShaer398, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![so-close](https://user-images.githubusercontent.com/73854999/199818202-53530cb4-baf4-42c1-a568-a6f6bd6b5e6e.gif)

## Highlights
- Linters are passing ✔
- Great UI design ✅

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-03 19:51 UTC, Lizdev-05 commented on index.html
> +    <div class="logo">My Logo</div>
Great job @ElShaer398👍, Kindly change the `div` to `a` tag so that your logo can serve as a link through which users can return back to the home page.

2022-11-03 19:51 UTC, Lizdev-05 commented on index.html
> +    <img src="images/nav.png" alt="nav">
Kindly wrap your hamburger in a `nav` tag so that it can follow the semantic convention.😉

2022-11-03 19:51 UTC, Lizdev-05 commented on index.html
> +    <div class="name">I'm Mohammad Glad to see you!</div>
Well done, I think it will be much better to put this in the `h1` tag, that way search engines will know it is a topic and also , this is what is acceptable semantically😎. You can check [this ](https://developer.mozilla.org/en-US/docs/Web/HTML/Element) link for more info.

2022-11-03 19:51 UTC, Lizdev-05 commented on index.html
> +      <a href="#"><i class="fa-brands fa-angellist"></i></a>
Kindly wrap these links inside the `ul` and `li` tags.
like these 👇
![li](https://user-images.githubusercontent.com/73854999/199820230-a7ba80c6-039d-453d-af5b-f6fcff262b5f.PNG)

2022-11-04 03:52 UTC, BregornOriginal approved these changes
Hi @ElShaer398 ,
Your project is complete!  There is nothing else to say other than... it's time to merge it 🥳 🥳 🥳 
Congratulations! 

## Highlights

✅ Linters are passing
✅ Correct use of GitHub Flow
✅ Good work making the changes requested 💯 💯 💯 

![giphy](https://user-images.githubusercontent.com/93630700/199881839-feb337a6-f41a-44bf-90c9-6f9a3af26ca6.gif)

## Optional suggestions

Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application.
Cheers and Happy coding!:aplauso::aplauso::aplauso:
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

Please, remember to tag me in your question so I can receive the notification.
------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)[.](https://airtable.com/shrQAqnBwek5a0O0s)._)

2022-11-04 15:03 UTC, merged