Toolbar-headline
ElShaer398/Portfolio-setup-and-mobile-first pull request #1
Opened 2022-12-02 22:06 UTC by ElShaer398

2022-12-02 22:49 UTC, abdulhamiid requested changes
# Status: Required Changes :recycle:
Hi @ElShaer398 👋, 
![Alt Text](https://c.tenor.com/vOLW_UQMySIAAAAC/almost-there.gif)
Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights 🌟

- ✔️ Descriptions are very descriptive
- ✔️ Linters checks are passing
- ✔️ Use GitHub Flow
- ✔️ Meaningful commit messages.

## Required Changes ♻️
_Please kindly check the comments under the review._

- [ ] Your pull request summary is empty 👇 
![image](https://user-images.githubusercontent.com/78251927/205402358-7e95e33f-90af-4b32-ae0e-05ab07d4fef4.png)

- [ ] In a way to document your work [in a professional way](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md), please summarize the task in your pull request summary, so the reviewer can have an idea about the pull request.

## Optional suggestions 🤷‍♂️
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

## Important Notes 📝
- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-02 22:49 UTC, abdulhamiid commented on index.html
> +  <section id="main_1" class="main-1">
- [ ] As per [project requirement](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/1_setup.md), please use Flexbox to align the content of this `section`.

2022-12-02 22:49 UTC, abdulhamiid commented on index.html
> +    <div class="description">I'm a software developer! I can help you build a product , feature or website Look through some of my work and experience! If you like what you see and have a project you
- [ ] Please, let's use a `p` tag here. that way, it will be semantically correct and the screen readers and other technologies will thank you 😎.

2022-12-02 22:49 UTC, abdulhamiid commented on index.html
> +    </ul>
- [ ] As per [project requirement](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/1_setup.md), please align the content of this section with Flexbox.

Your design 👇 
![image](https://user-images.githubusercontent.com/78251927/205401046-79718be9-0734-4827-af7a-2212e54f1f2b.png)

Figma design 👇 
![image](https://user-images.githubusercontent.com/78251927/205400991-8646b433-bcdf-4845-8833-ae4de59fa333.png)

- [ ] Also, let us add the missing icon to match [the templates in Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1). (you have included only four instead of five icons 😊) please let us fix that.

2022-12-02 22:49 UTC, abdulhamiid commented on main.css
> +}
- [ ] Please let us remove the `fixed` width `width: 375px`, the mobile version should be responsive until the desktop screen size.

2022-12-02 22:49 UTC, abdulhamiid commented on README.md
> +This project is MIT licensed.
- [ ] Please, kindly make your README file more descriptive. let us copy and customize the contents of this [README template](https://github.com/microverseinc/readme-template) accordingly.

- [ ] The purpose of README is to introduce and explain a project. It contains information that is commonly required to understand what the project is about. so please update your readme by providing other people with information about your project 😊

2022-12-02 22:52 UTC, abdulhamiid commented on index.html
> +  <section id="main_1" class="main-1">
Referring to this section 👇 
```
<section id="main_1" class="main-1">
```

2022-12-02 22:53 UTC, abdulhamiid commented on index.html
> +    <div class="description">I'm a software developer! I can help you build a product , feature or website Look through some of my work and experience! If you like what you see and have a project you
Reffering to this 👇 
```
 <div class="description">I'm a software developer! I can help you build a product , feature or website Look through some of my work and experience! If you like what you see and have a project you need coded, don't hestiate to contact me.</div>
```

2022-12-03 04:07 UTC, Tadesse-Alemayehu requested changes
### Hi @ElShaer398 

### I'm Tadesse Alemayehu your reviewer for this PR. :hand: 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![199733072-bdacca19-8df9-43a7-be93-3aff2f1c15c8](https://user-images.githubusercontent.com/69077061/204107907-c2532abb-b23d-4fda-88f0-1ec9c7b71971.gif)

 ## Highlights
 - [ ] Good job making most of the changes requested by the previous reviewer. 🙏
 - [ ] Good job overall following the template design 💯
 - [ ]  Correct GitHub Flow 👍🏾
 - [ ]  Good commit history 🥇
 - [ ]  Good PR title/description 💯
 - [ ]  All linters passed 🥇

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-03 04:07 UTC, Tadesse-Alemayehu commented on README.md
> +<p align="right">(<a href="#readme-top">back to top</a>)</p>
- [ ] Dear @ElShaer398, Good job using the provided template for your readme. But as the previous code reviewer mentioned README `contains information that is commonly required to understand what the project is about`. In your case, your readme does not discuss about the project itself or the author. Please make sure every detail in your readme talks about the project or the author (you). `CUSTOMIZE YOUR README ACCORDING TO YOUR PROJECT INFO`
> Note: feel free to leave empty some of the headings if you don't have the relevant information to add.

2022-12-03 04:48 UTC, amejid approved these changes
Hi @ElShaer398 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
<img src="https://media3.giphy.com/media/YKdm91XONLTaw/giphy-downsized-medium.gif"/>
## Highlights
- Professional README :heavy_check_mark: 
- Descriptive PR :heavy_check_mark: 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-03 16:24 UTC, merged